<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wok_photostation"
 *
 * Auto generated by Extension Builder 2020-05-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PhotoStation',
    'description' => 'Extension with plugin for display of PhotoStation 6.0 albums (stored on a Synology DiskStation) in TYPO3 frontend',
    'category' => 'plugin',
    'author' => 'Wolfgang Kleinbach',
    'author_email' => 'info@zeichensatz.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
